services:
  app_proxy:
    environment:
      APP_HOST: rapougnac-opengist_opengist_1
      APP_PORT: 6157
  opengist:
    image: ghcr.io/thomiceli/opengist:1.7.1
    restart: unless-stopped
    ports:
      - "${APP_OPENGIST_SSH_PORT}:2222"
    volumes:
      - ${APP_DATA_DIR}/data/opengist:/opengist
    environment:
      UID: 1000
      GID: 1000
