version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: rapougnac-jellystat_jellystat_1
      APP_PORT: 9680
  jellystat-db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
    - ${APP_DATA_DIR}/data/postgresql:/var/lib/postgresql/data
  jellystat:
    image: cyfershepard/jellystat:1.0.9
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'my-secret-jwt-key'
    ports:
      - "3000:3000" #Server Port
    volumes:
      - ${APP_DATA_DIR}/data/backup-data:/app/backend/backup-data

    depends_on:
      - jellystat-db
    restart: unless-stopped
networks:
  default:
