services:
  app_proxy:
    environment:
      APP_HOST: rapougnac-ryot_ryot_1
      APP_PORT: 8000
  ryot-db:
    image: postgres:16-alpine # atleast version 15 is required
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  ryot:
    image: ghcr.io/ignisda/ryot:latest
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - FRONTEND_INSECURE_COOKIES=true # if running on HTTP
    pull_policy: always

volumes:
  postgres_storage:
