services:
  app_proxy:
    environment:
      APP_HOST: rapougnac-sillytavern_sillytavern_1
      APP_PORT: 8000
    depends_on:
      - sillytavern
  sillytavern:
    image: ghcr.io/sillytavern/sillytavern:release
    restart: unless-stopped
