services:
  app_proxy:
    environment:
      APP_HOST: rapougnac-sillytavern_sillytavern_1
      APP_PORT: 8000
  sillytavern:
    image: ghcr.io/sillytavern/sillytavern:release
    restart: unless-stopped
    volumes:
      - "${APP_DATA_DIR}/config.yaml:/home/node/app/config.yaml"
