version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: rapougnac-grafana_grafana_1
      APP_PORT: 3000

  grafana:
    image: grafana/grafana-entreprise:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ${APP_DATA_DIR}/data:/var/lib/grafana
