services:
  app_proxy:
    environment:
      APP_HOST: rapougnac-grafana_grafana_1
      APP_PORT: 3000

  grafana:
    image: grafana/grafana-enterprise:10.4.2
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ${APP_DATA_DIR}/data:/var/lib/grafana
    networks:
      - prometheus_prom

networks:
  prometheus_prom:
    external: true