services:
  app_proxy:
    environment:
      APP_HOST: rapougnac-wakapi_wakapi_1
      APP_PORT: 3000
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/wakapi:/data
    environment:
      WAKAPI_EXPOSE_METRICS: true
      WAKAPI_PASSWORD_SALT: '${SALT}'
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/prometheus:/prometheus
      - ${APP_DATA_DIR}/data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    environment:
      PROMETHEUS_CONFIG_FILE: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - wakapi
