services:
  app_proxy:
    environment:
      APP_HOST: rapougnac-wakapi_wakapi_1
      APP_PORT: 3000
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/wakapi:/data
    environment:
      WAKAPI_EXPOSE_METRICS: true
      WAKAPI_PASSWORD_SALT: '${SALT}'
